development:
  adapter: redis

test:
  adapter: redis

staging:
  adapter: redis
  url: redis://45.55.180.23:8076
  channel_prefix: parkourutah_staging

production:
  adapter: redis
  url: redis://45.55.180.23:8075
  channel_prefix: parkourutah_production
